
## What is NumPy?

<img src="numpy-6-step-ml-framework-tools-numpy-highlight.png" alt="a 6 step machine learning framework along will tools you can use for each step" width="700"/>


In [6]:
tup = (3,)


In [7]:
type(tup)

tuple

In [8]:
tup1=("as",)
type(tup1)

tuple

### Anatomy of an array

<img src="numpy-anatomy-of-a-numpy-array.png" alt="anatomy of a numpy array"/>

Key terms:
* **Array** - A list of numbers, can be multi-dimensional.
* **Scalar** - A single number (e.g. `7`).
* **Vector** - A list of numbers with 1-dimesion (e.g. `np.array([1, 2, 3])`).
* **Matrix** - A (usually) multi-deminsional list of numbers (e.g. `np.array([[1, 2, 3], [4, 5, 6]])`).

# 1. Data types and attributes

In [9]:
# shape
# dim
# datatype
# size

In [11]:
import numpy as np
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [14]:
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [15]:
a2 = np.array([[1,2,3],
               [4,5,6]])

In [16]:
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [18]:
a21 = np.array([[1,2,3],
               [4,5.4,6]])

In [19]:
a21.shape, a21.ndim, a21.dtype, a21.size, type(a21)

((2, 3), 2, dtype('float64'), 6, numpy.ndarray)

In [20]:
a21

array([[1. , 2. , 3. ],
       [4. , 5.4, 6. ]])

In [ ]:
a21 = np.array([[1,2,3],
               [4,5.4,6]])

In [21]:
a3 = np.array([[[1,2,3],
           [4,5,6],
           [7,8,9]],
          
          [[10,11,12],
           [13,14,15],
           [16,17,18]]])

a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [22]:
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [23]:
a31 = np.array([[[1,2,3],
           [4,5,6],
           [7,8,9]],
                
            [[1,2,3],
           [4,5,6],
           [7,8,9]],
          
          [[10,11,12],
           [13,14,15],
           [16,17,18]]])

a31

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [25]:
a31.shape, a31.ndim

((3, 3, 3), 3)

# Creating Array

In [ ]:
# np.arange()
# np.ones()
# np.zeros()
# np.eye()
# np.random.randn / randint/ rand

In [26]:
lis = [10,20,30,40,50]
lis_arr = np.array(lis)
lis_arr

array([10, 20, 30, 40, 50])

In [28]:
r1 = [1,2,3]
r2 = [4,5,6]
r3 = [7,8,9]

d2_arr = np.array([r1,r2,r3])
d2_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
d2_arr.ndim, d2_arr.shape

(2, (3, 3))

In [30]:
nu_arr = np.arange(5,11) # star => 5, end=> 11
nu_arr

array([ 5,  6,  7,  8,  9, 10])

In [31]:
nu_arr_1 = np.arange(5,11,2) # star => 5, end=> 11
nu_arr_1

array([5, 7, 9])

In [32]:
nu_on = np.ones(6)
nu_on

array([1., 1., 1., 1., 1., 1.])

In [33]:
nu_on_1 = np.ones((6,4))
nu_on_1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
nu_on_1.dtype

dtype('float64')

In [35]:
nu_ze = np.zeros(5)
nu_ze

array([0., 0., 0., 0., 0.])

In [36]:
nu_ze_1 = np.zeros((5,4))
nu_ze_1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
nu_ey = np.eye(3) # sqaure mat
nu_ey

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
ny_arr = np.array(['red','blu', 'green'])
ny_arr

array(['red', 'blu', 'green'], dtype='<U5')

In [41]:
ny_1 = np.append(ny_arr,'yellow')
ny_1

array(['red', 'blu', 'green', 'yellow'], dtype='<U6')

In [42]:
ny_2 = np.append(ny_arr,['black', 'white'])
ny_2

array(['red', 'blu', 'green', 'black', 'white'], dtype='<U5')

In [43]:
ny_ze = np.zeros((3,3))
ny_ze

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
ny_ze_1 = np.append(ny_ze,[[1,2,3]], axis = 0)
ny_ze_1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 2., 3.]])

In [45]:
ny_ze_2 = np.append(ny_ze,[[1],[2],[3]],axis = 1)
ny_ze_2

array([[0., 0., 0., 1.],
       [0., 0., 0., 2.],
       [0., 0., 0., 3.]])

In [46]:
ny_2

array(['red', 'blu', 'green', 'black', 'white'], dtype='<U5')

In [47]:
# delete
ny_2_del = np.delete(ny_2,3)
ny_2_del

array(['red', 'blu', 'green', 'white'], dtype='<U5')

In [49]:
int_rand = np.random.randint(1,11)
int_rand

10

In [51]:
int_rand_1 = np.random.randint(1,11,5)
int_rand_1

array([1, 4, 9, 1, 7])

In [53]:
int_rand_2 = np.random.randint(1,11,size = (5,4))
int_rand_2

array([[ 3,  9,  9,  3],
       [ 1,  9, 10,  3],
       [ 4,  1,  4,  5],
       [ 7, 10,  2, 10],
       [ 4,  4,  2, 10]])

In [54]:
int_rand_del_1 = np.delete(int_rand_2, 4, axis = 0)
int_rand_del_1

array([[ 3,  9,  9,  3],
       [ 1,  9, 10,  3],
       [ 4,  1,  4,  5],
       [ 7, 10,  2, 10]])

In [55]:
int_rand_2

array([[ 3,  9,  9,  3],
       [ 1,  9, 10,  3],
       [ 4,  1,  4,  5],
       [ 7, 10,  2, 10],
       [ 4,  4,  2, 10]])

In [56]:
int_rand_del_2 = np.delete(int_rand_2, 0, axis = 1)
int_rand_del_2

array([[ 9,  9,  3],
       [ 9, 10,  3],
       [ 1,  4,  5],
       [10,  2, 10],
       [ 4,  2, 10]])

In [57]:
from scipy import linalg
A = np.array([[1,9,2,1,1],
             [10,1,2,1,1],
             [1,0,5,1,1],
             [2,1,1,2,9],
             [2,1,2,13,2]])
A

array([[ 1,  9,  2,  1,  1],
       [10,  1,  2,  1,  1],
       [ 1,  0,  5,  1,  1],
       [ 2,  1,  1,  2,  9],
       [ 2,  1,  2, 13,  2]])

In [58]:
B = np.array([170,180,140,180,350]).reshape((5,1))
B

array([[170],
       [180],
       [140],
       [180],
       [350]])

In [59]:
X=linalg.solve(A,B)
X

array([[10.],
       [10.],
       [20.],
       [20.],
       [10.]])